/* ─── Incidencias — Constants & Mock Data ── */

const MOCK_STUDENTS = [
  {
    id: "st1",
    nombre: "Sebasti\u00e1n",
    apellido: "Torres R\u00edos",
    seccion: "primaria",
    grado: "4\u00b0",
    grupo: "A",
  },
  {
    id: "st2",
    nombre: "Daniela",
    apellido: "Guzm\u00e1n P\u00e9rez",
    seccion: "primaria",
    grado: "5\u00b0",
    grupo: "B",
  },
  {
    id: "st3",
    nombre: "Mateo",
    apellido: "Herrera Campos",
    seccion: "primaria",
    grado: "6\u00b0",
    grupo: "A",
  },
  {
    id: "st4",
    nombre: "Valeria",
    apellido: "Morales Soto",
    seccion: "primaria",
    grado: "3\u00b0",
    grupo: "A",
  },
  {
    id: "st5",
    nombre: "Diego",
    apellido: "Ram\u00edrez Luna",
    seccion: "secundaria",
    grado: "1\u00b0",
    grupo: "B",
  },
  {
    id: "st6",
    nombre: "Sof\u00eda",
    apellido: "Mendoza Vega",
    seccion: "secundaria",
    grado: "2\u00b0",
    grupo: "A",
  },
  {
    id: "st7",
    nombre: "Emilio",
    apellido: "Castro Flores",
    seccion: "secundaria",
    grado: "3\u00b0",
    grupo: "B",
  },
  {
    id: "st8",
    nombre: "Andrea",
    apellido: "Jim\u00e9nez Ruiz",
    seccion: "secundaria",
    grado: "1\u00b0",
    grupo: "A",
  },
  {
    id: "st9",
    nombre: "Carlos",
    apellido: "Vargas Ortiz",
    seccion: "secundaria",
    grado: "2\u00b0",
    grupo: "C",
  },
  {
    id: "st10",
    nombre: "Camila",
    apellido: "Reyes Navarro",
    seccion: "bachillerato",
    grado: "1\u00b0",
    grupo: "A",
  },
  {
    id: "st11",
    nombre: "Rodrigo",
    apellido: "Salinas D\u00edaz",
    seccion: "bachillerato",
    grado: "2\u00b0",
    grupo: "B",
  },
  {
    id: "st12",
    nombre: "Isabella",
    apellido: "Pe\u00f1a Romero",
    seccion: "bachillerato",
    grado: "3\u00b0",
    grupo: "A",
  },
  {
    id: "st13",
    nombre: "Luna",
    apellido: "Carrillo Santos",
    seccion: "preescolar",
    grado: "2\u00b0",
    grupo: "A",
  },
  {
    id: "st14",
    nombre: "Mat\u00edas",
    apellido: "L\u00f3pez Rojas",
    seccion: "preescolar",
    grado: "3\u00b0",
    grupo: "B",
  },
  {
    id: "st15",
    nombre: "Valentina",
    apellido: "N\u00fa\u00f1ez Espinoza",
    seccion: "maternal",
    grado: "Lactantes",
    grupo: "A",
  },
];

const MOCK_INCIDENTS = [
  {
    id: "i1",
    alumnoId: "st2",
    titulo: "Tardanza reiterada",
    descripcion:
      "Lleg\u00f3 tarde en 3 ocasiones durante la semana sin justificante.",
    categoria: "asistencia",
    gravedad: "leve",
    fecha: "2026-05-06",
    registradoPor: "Miss Lila Meza",
    seccion: "primaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i2",
    alumnoId: "st3",
    titulo: "Da\u00f1o a silla del sal\u00f3n",
    descripcion:
      "Ray\u00f3 la silla con un comp\u00e1s causando da\u00f1o al mobiliario.",
    categoria: "dano",
    gravedad: "leve",
    fecha: "2026-04-28",
    registradoPor: "Miss Lila Meza",
    seccion: "primaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i3",
    alumnoId: "st3",
    titulo: "Incumplimiento de uniforme",
    descripcion:
      "Asisti\u00f3 tres d\u00edas consecutivos sin el su\u00e9ter reglamentario.",
    categoria: "uniforme",
    gravedad: "leve",
    fecha: "2026-05-12",
    registradoPor: "Miss Lila Meza",
    seccion: "primaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i4",
    alumnoId: "st5",
    titulo: "Agresi\u00f3n f\u00edsica a compa\u00f1ero",
    descripcion:
      "Agredi\u00f3 f\u00edsicamente a un compa\u00f1ero durante el receso. Intervino el prefecto de guardia.",
    categoria: "agresion",
    gravedad: "grave",
    fecha: "2026-05-14",
    registradoPor: "Ing. Jared Camacho",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i5",
    alumnoId: "st5",
    titulo: "Falta de respeto a docente",
    descripcion:
      "Respondi\u00f3 de forma grosera a la maestra de espa\u00f1ol frente al grupo.",
    categoria: "lenguaje",
    gravedad: "media",
    fecha: "2026-05-08",
    registradoPor: "Ing. Jared Camacho",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i6",
    alumnoId: "st6",
    titulo: "Cort\u00f3 el cabello a compa\u00f1era",
    descripcion:
      "Durante clase de educaci\u00f3n art\u00edstica cort\u00f3 un mech\u00f3n de cabello a su compa\u00f1era de banca con las tijeras del material.",
    categoria: "agresion",
    gravedad: "grave",
    fecha: "2026-05-20",
    registradoPor: "Miss Erika Castro",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i7",
    alumnoId: "st6",
    titulo: "Conducta disruptiva en clase",
    descripcion:
      "Interrumpi\u00f3 la clase en varias ocasiones burl\u00e1ndose de respuestas de compa\u00f1eros.",
    categoria: "conducta",
    gravedad: "leve",
    fecha: "2026-05-05",
    registradoPor: "Miss Erika Castro",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i8",
    alumnoId: "st6",
    titulo: "Lenguaje soez en clase",
    descripcion:
      "Uso reiterado de vocabulario ofensivo en el sal\u00f3n durante las sesiones.",
    categoria: "lenguaje",
    gravedad: "media",
    fecha: "2026-04-22",
    registradoPor: "Miss Erika Castro",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i9",
    alumnoId: "st7",
    titulo: "Tardanza reiterada",
    descripcion:
      "Lleg\u00f3 tarde los primeros d\u00edas del periodo sin justificaci\u00f3n.",
    categoria: "asistencia",
    gravedad: "leve",
    fecha: "2026-03-10",
    registradoPor: "Prof. Fernando Paulino",
    seccion: "secundaria",
    estado: "resuelta",
    resolucion:
      "Habl\u00f3 con los padres. Se comprometieron a llegar temprano.",
  },
  {
    id: "i10",
    alumnoId: "st7",
    titulo: "Incumplimiento de tareas",
    descripcion:
      "No entreg\u00f3 tareas de matem\u00e1ticas en dos semanas consecutivas.",
    categoria: "conducta",
    gravedad: "leve",
    fecha: "2026-04-15",
    registradoPor: "Prof. Fernando Paulino",
    seccion: "secundaria",
    estado: "resuelta",
    resolucion: "Firm\u00f3 compromiso junto con sus padres.",
  },
  {
    id: "i11",
    alumnoId: "st7",
    titulo: "Uso de celular en examen",
    descripcion:
      "Se le encontr\u00f3 usando el celular durante el examen de biolog\u00eda.",
    categoria: "conducta",
    gravedad: "media",
    fecha: "2026-05-18",
    registradoPor: "Prof. Fernando Paulino",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i12",
    alumnoId: "st8",
    titulo: "Inasistencia sin justificante",
    descripcion:
      "Falt\u00f3 un d\u00eda sin avisar previamente a la instituci\u00f3n.",
    categoria: "asistencia",
    gravedad: "leve",
    fecha: "2026-03-22",
    registradoPor: "Miss Lila Meza",
    seccion: "secundaria",
    estado: "resuelta",
    resolucion: "Present\u00f3 justificante m\u00e9dico al d\u00eda siguiente.",
  },
  {
    id: "i13",
    alumnoId: "st9",
    titulo: "Da\u00f1o a propiedad escolar",
    descripcion:
      "Ray\u00f3 y da\u00f1\u00f3 una mesa del laboratorio de qu\u00edmica con un instrumento punzante.",
    categoria: "dano",
    gravedad: "grave",
    fecha: "2026-05-15",
    registradoPor: "Ing. Jared Camacho",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i14",
    alumnoId: "st9",
    titulo: "Insultos a compa\u00f1ero",
    descripcion:
      "Se dirigi\u00f3 de manera ofensiva y discriminatoria hacia un compa\u00f1ero frente al grupo.",
    categoria: "lenguaje",
    gravedad: "media",
    fecha: "2026-05-09",
    registradoPor: "Ing. Jared Camacho",
    seccion: "secundaria",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i15",
    alumnoId: "st11",
    titulo: "Falta de respeto a docente",
    descripcion:
      "Cuestion\u00f3 de manera agresiva la calificaci\u00f3n de su examen frente al grupo.",
    categoria: "conducta",
    gravedad: "media",
    fecha: "2026-05-19",
    registradoPor: "Ing. Eduardo Torbellin",
    seccion: "bachillerato",
    estado: "activa",
    resolucion: null,
  },
  {
    id: "i16",
    alumnoId: "st11",
    titulo: "Ausencia en examen final",
    descripcion:
      "No se present\u00f3 al examen final de f\u00edsica sin justificaci\u00f3n previa.",
    categoria: "asistencia",
    gravedad: "leve",
    fecha: "2026-05-12",
    registradoPor: "Ing. Eduardo Torbellin",
    seccion: "bachillerato",
    estado: "activa",
    resolucion: null,
  },
];

const CATEGORIES = [
  { id: "conducta", label: "Conducta inapropiada" },
  { id: "agresion", label: "Agresi\u00f3n f\u00edsica" },
  { id: "lenguaje", label: "Lenguaje ofensivo" },
  { id: "dano", label: "Da\u00f1o a propiedad" },
  { id: "asistencia", label: "Inasistencia / Tardanza" },
  { id: "uniforme", label: "Incumplimiento de uniforme" },
  { id: "otro", label: "Otro" },
];

const CAT_LABEL = Object.fromEntries(CATEGORIES.map((c) => [c.id, c.label]));

const SEMAFORO = {
  verde: {
    color: "#15803d",
    bg: "#dcfce7",
    border: "#86efac",
    label: "Sin antecedentes",
  },
  amarillo: {
    color: "#b45309",
    bg: "#fef9c3",
    border: "#fde047",
    label: "En observaci\u00f3n",
  },
  rojo: {
    color: "#b91c1c",
    bg: "#fee2e2",
    border: "#fca5a5",
    label: "Requiere atenci\u00f3n",
  },
};

const GRAVEDAD = {
  leve: { label: "Leve", color: "#15803d", bg: "#dcfce7" },
  media: { label: "Media", color: "#b45309", bg: "#fef9c3" },
  grave: { label: "Grave", color: "#b91c1c", bg: "#fee2e2" },
};

window.MOCK_STUDENTS = MOCK_STUDENTS;
window.MOCK_INCIDENTS = MOCK_INCIDENTS;
window.CATEGORIES = CATEGORIES;
window.CAT_LABEL = CAT_LABEL;
window.SEMAFORO = SEMAFORO;
window.GRAVEDAD = GRAVEDAD;
